In [3]:
import numpy as np

# Gauss Elimination
This algorithm is used to solve the system of equation $Ax=b$ to obtain the unknow vector $x$. It involved forward elimination to transform the matrix into an upper triangular matrix. Subsequently, backward substitution is used to calculate the unknown vector elements. In the following function, both "naive" and partial pivoting implementation of this algorithm is considered. A switch is considered in the input arguments; if the switch if set to `False`, the function operates without pivoting, i.e., the naive implementation; alternatively, if the switch if `True` (which is the default value), the function does partial pivoting.

In [4]:
def gaussElim(A, b, pivot = True):   #function definition
    """
    Solves the system of equations using Gauss Elimination method
    
    gaussElimNaive(A, b, pivot = True)
    Solves the system of equations Ax=b to obtain x using Gauss Elimination method
    Input:
        A: a square matrix 
        b: the right-hand side vector
        pivot: if True partial pivoting is performed, 
               if False no pivoting is performed (default: True)
    Output
        x: the unknown vector
    """
    # check if A is a square matrix, if not show an error message
    assert A.shape[0] == A.shape[1], "A is not a square matrix"
    # check if A, b shapes are consistent, if not show an error message
    assert A.shape[0] == b.shape[0], "A and b shapes do not match"
    n = A.shape[0]  #save the number of rows of the matrix
    # make local copies of A and b so that the original copies are not over-written
    A1 = A.copy()
    b1 = b.copy()
    x = np.zeros(n)   #initiate x vector of size n filled with zeros
    # forward elimination
    for i in range(0, n-1):           #the pivot row i ranging from 0 to n-2
        if pivot :                    #partial pivoting?
            imax = list(abs(A1)[:,i]).index(abs(A1[i:n,:]).max(0)[i]) #finds the row index of the max. absolute value in column i of A1 
                                                                      # abs(A1[i:n,:]).max(0)[i] is the max value
                                                                      # the list().index attributes returns the row index corresponding to 
                                                                      # the max value
            if i != imax :                   #if max occurs at a different location than i
                A1[[i,imax]] = A1[[imax,i]]  #switch the i and imax rows for both A1 and b1
                b1[[i,imax]] = b1[[imax,i]]
        for j in range(i+1, n):      #rows below pivot from i+1 to n-1
            f = - A1[j,i]/A1[i,i]    #A[i,i] is the pivot element. Factor f 
                                     #      is calculated for all subsequent rows
            A1[j,i:n] = A1[j,i:n] + f * A1[i,i:n]  #using pivot element to eliminate/modify 
                                                   #elements below pivot row for all columns
            b1[j] = b1[j] + f * b1[i]              #modify the RHS vector accordingly
    # at this stage an upper triangle matrix results
    # back substitution
    x[n-1] = b1[n-1] / A1[n-1, n-1]  #calculate x on the last row
    for i in range(n-2,-1,-1):       #calculate x for row i from n-2 down to 0
        sum = 0.
        for k in range(i+1, n):
            sum = sum + A1[i, k] * x[k]   # sum of Ax for columns i+1 to n-1
        x[i] =  (b1[i] - sum) / A1[i, i]  #calculate x for row i
    return x  #return x 

# Gauss Elimination Naive
This is the basic implementation of Gauss Elimination. It is called "naive" because no care is taken to pivot element based on theor values. As a result, there is a chance that round-off error can influence the results quite significantly. This shortcoming needs to be take into consideration. 



## Example
Solve the system $Ax=b$ with $A=\begin{bmatrix}
-5 & 2 & -1\\
1 & 2 & 7\\
-4 & 3 & 4\\
\end{bmatrix}$ and the vector $b=\begin{bmatrix}
3\\
1\\
4\\
\end{bmatrix}$ using Gauss Elimination Naive

In [5]:
A = np.array([[-5., 2., -1.],[1., 2., 7.],[-4., 3., 4.]]) 
b = np.array([3.,1.,4.])
x = gaussElim(A,b, False)   #pivot=False -> Naive Gauss Elimination
print('A = \n',A)
print('b = \n',b)
print('x = \n',x)


A = 
 [[-5.  2. -1.]
 [ 1.  2.  7.]
 [-4.  3.  4.]]
b = 
 [3. 1. 4.]
x = 
 [-1.4 -1.6  0.8]


Checking the results by multiplying $Ax$ to see if it gives vector $b$:

In [ ]:
ax = np.dot(A,x)
print('Ax = \n',ax)
print('b = \n',b)


Ax = 
 [3. 1. 4.]
b = 
 [3. 1. 4.]


$Ax=b$ is satisfied. Therefore $x$ is the solution to this system.

# Gauss Elimination With Pivoting
To avoid the round-off error issues,  every time a pivot element is to be selected, all the element in the same column below that element are checked and the largest element (in mangnitude) is selected as pivot. The rows are rearranged such that the corresponding equation becomes the pivot equation on top (not necessarily the first equation). Subsequently, forward elimination is performed. "Partial pivoting" means that the pivoting (i.e., switching) is applied to rows only and not columns. In "full" pivoting both rows and columns are switches which is not considered here.

## Example
Solve the system $Ax=b$ with $A=\begin{bmatrix}
1 & 2 & 3 & -2\\
3 & 0.5 & -5 & 50 \\
3 & 4 & 20 &-1 \\
-2\times 10^7 &7 &2 &3
\end{bmatrix}$ and the vector $b=\begin{bmatrix}
10^7\\
4\\
5\\
-2
\end{bmatrix}$ using Gauss Elimination without (Naive) and with pivoting. Compare the results.


Without pivoting (Naive) solution gives:

In [ ]:
A=np.array([[1.,2.,3., -2.],[3.,0.5,-5., 50.],[3.,4.,20.,-1.],[-2.0e7,7.,2.,3.]]) 
b = np.array([1.e7,4.,5.,-2.])
x = gaussElim(A,b,False)   #pivot=False -> Naive Gauss Elimination
print('A = \n',A)
print('b = \n',b)
print('... without pivoting (naive):')
print('x = \n',x)
print('Ax=',np.dot(A,x))

A = 
 [[ 1.e+00  2.e+00  3.e+00 -2.e+00]
 [ 3.e+00  5.e-01 -5.e+00  5.e+01]
 [ 3.e+00  4.e+00  2.e+01 -1.e+00]
 [-2.e+07  7.e+00  2.e+00  3.e+00]]
b = 
 [ 1.e+07  4.e+00  5.e+00 -2.e+00]
... without pivoting (naive):
x = 
 [ 2.23472519e+00  6.86917357e+06 -1.38419034e+06 -2.07110824e+05]
Ax= [ 1.00000000e+07  4.00000000e+00  5.00000000e+00 -2.04854741e+00]


As seen $Ax$ is slightly different from $b$. Trying the solution with pivoting:

In [ ]:
print('... with pivoting:')
xpiv = gaussElim(A,b,True)   #pivot= True ->  Gauss Elimination with pivoting
print('x w/ pivoting= \n',xpiv)
print('Ax=',np.dot(A,xpiv))
print('b = \n',b)

... with pivoting:
x w/ pivoting= 
 [ 2.23472519e+00  6.86917357e+06 -1.38419034e+06 -2.07110824e+05]
Ax= [ 1.00000000e+07  4.00000000e+00  5.00000000e+00 -1.99999999e+00]
b = 
 [ 1.e+07  4.e+00  5.e+00 -2.e+00]


Pivoting improves the result and $Ax=b$ is more accurately satisfied. However, we notice the the solution $x$ vector appears to be similar for with and without pivoting case. This is because the change to $x$ is small here. To highlight the change in $x$, we out the difference between with and without pivoting results:


In [ ]:
print('The difference between with and without pivoting solution vectors:')
print('x - xpiv = \n', x - xpiv)

The difference between with and without pivoting solution vectors:
x - xpiv = 
 [ 2.42737030e-09  0.00000000e+00 -4.65661287e-10 -1.16415322e-10]


As seen, despite that the change in $x$ is small, the error obtained with non-pivoting solution is quite significant. The solution with pivoting is more accurate as it satifies $Ax=b$ more accurately.

## Exercise
Consider the matrix $A=\begin{bmatrix}
5 & 3 & 2\\
0 & 1 & 9\\
-4 & 6 & 7\\
\end{bmatrix}$ and the vector $b=\begin{bmatrix}
11\\
3\\
2\\
\end{bmatrix}$.  Solve the system of equations $Ax=b$ to obtain vector $x$. Check to see if $Ax=b$ is satisfied with the vector $x$ you obtained.