# LU factorization (decomposition)

LU factorization or decomposition factors a matrix as the product of a lower triangular matrix ($L$) and an upper triangular matrix ($U$). When doing LU factorization with partial pivoting a permutaiton matrix ($P$) is also introduced.

In python, the built-in function [lu](https://docs.scipy.org/doc/scipy-0.13.0/reference/generated/scipy.linalg.lu.html), which is a part of `scipy.linalg` package, is used for LU factorization with partial pivoting.


**Note: the permutation matrix $P$ that keeps track of rows switched is the transpose of the permutation matrix that the python lu function returns (denoted as $P_T$).** Therefore, we have $PA=LU$ or $A=P_TLU$, where $A$ is the coefficient matrix.

### Example: 

Perform LU factorization of the matrix $A$ given below.

In [ ]:
import numpy as np
from scipy.linalg import lu, inv

A = np.array([[4., 6., 9.],[2., 1., 8.], [11., 5., 3.]])
PT,L,U = lu(A)   #lu function: does LU factorization with pivoting
print('A=\n', A)

P = PT.T # Note that the permutation matrix if the transpose of what lu returns
         # P is the matrix keeing track of row switching not PT
print('P=\n', P)

print('L=\n', L)
print('U=\n', U)
LU = np.dot(L,U)   
print('[L][U]=\n',LU)
PA = np.dot(P,A)
print('[P][A]=\n', PA, '= [L][U] : Verified')
print('We can also check using PT as follows:')
print('[PT][L][U]=\n', np.dot(PT,LU), '-> [PT][L][U]=[A] : Verified')


A=
 [[ 4.  6.  9.]
 [ 2.  1.  8.]
 [11.  5.  3.]]
P=
 [[0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]]
L=
 [[1.         0.         0.        ]
 [0.36363636 1.         0.        ]
 [0.18181818 0.02173913 1.        ]]
U=
 [[11.          5.          3.        ]
 [ 0.          4.18181818  7.90909091]
 [ 0.          0.          7.2826087 ]]
[L][U]=
 [[11.  5.  3.]
 [ 4.  6.  9.]
 [ 2.  1.  8.]]
[P][A]=
 [[11.  5.  3.]
 [ 4.  6.  9.]
 [ 2.  1.  8.]] = [L][U] : Verified
We can also check using PT as follows:
[PT][L][U]=
 [[ 4.  6.  9.]
 [ 2.  1.  8.]
 [11.  5.  3.]] -> [PT][L][U]=[A] : Verified


## Solution of a system using LU factorization

To solve the system of equations $Ax=b$ using LU factorization (with partial pivoting):
* Factorize $A$ into $L$ and $U$
* Solve $Ld=Pb$ to obtain $d$ vector
* Solve $Ux=d$ to obtain $x$ vector

### Example: 

Solve $Ax=b$ using LU factorization where matrix $A$ and vector $b$ given below. Check the result by solving the system directly.

In [ ]:
A = np.array([[4., 6., 9.],[2., 1., 8.], [11., 5., 3.]])
b = np.array([16., 8., 23.])
print('A=\n', A)
print('b=', b)
print('-----------')
PT,L,U = lu(A)
P = PT.T # Note that the permutation matrix if the transpose of what lu returns
         # P is the matrix keeing track of row switching not PT
print('P=\n', P)
print('L=\n', L)
print('U=\n', U)

print('Solve Ld=Pb:')
b1 = np.dot(P,b)
d = np.linalg.solve(L,b1)
print('d=', d)
print('Solve Ux=d:')
x = np.linalg.solve(U,d)
print('x=', x)
print('Check by multiplying Ax:')
print('Ax=',np.dot(A,x),'= b : verified')

print('-------')
print('Check by solving Ax=b directly:')
x = np.linalg.solve(A,b)
print('x=', x)
print('Ax=',np.dot(A,x))



A=
 [[ 4.  6.  9.]
 [ 2.  1.  8.]
 [11.  5.  3.]]
b= [16.  8. 23.]
-----------
P=
 [[0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]]
L=
 [[1.         0.         0.        ]
 [0.36363636 1.         0.        ]
 [0.18181818 0.02173913 1.        ]]
U=
 [[11.          5.          3.        ]
 [ 0.          4.18181818  7.90909091]
 [ 0.          0.          7.2826087 ]]
Solve Ld=Pb:
d= [23.          7.63636364  3.65217391]
Solve Ux=d:
x= [1.55522388 0.87761194 0.50149254]
Check by multiplying Ax:
Ax= [16.  8. 23.] = b : verified
-------
Check by solving Ax=b directly:
x= [1.55522388 0.87761194 0.50149254]
Ax= [16.  8. 23.]


# Exercise:

Consider the system of equations $[A]\{x\}=\{b\}$ described as
\begin{eqnarray}
8x_1+x_{2}-5x_{3}&=&9 \\
3x_1-6x_{2}+7x_{3}&=&18 \\
4x_1+17x_{2}+8x_{3}&=&14 \\
\end{eqnarray}

Perform LU factorization of $[A]$. Solve this system using LU factorization. Check the solution and verify that $[A]\{x\}=\{b\}$ is satisfies.