# Basic Matrix operations

In [ ]:
import numpy as np

## Creating an array
There are several ways to create an array in python:



1) One way is to use the `array(list [,type(optional)])` function to turn a list into an array.

In [ ]:
a = np.array([[3.0, 1.0],[-2.0, 4.0]])
print(a)
b = np.array([[3.0, 1.0],[-2.0, 4.0]],int)  # an array of integers
print('array of integers:')
print(b)
c = np.array([[3.0, 1.0],[-2.0, 4.0]],float)  # an array of floating point numbers
print('array of floating point numbers:')
print(c)


[[ 3.  1.]
 [-2.  4.]]
array of integers:
[[ 3  1]
 [-2  4]]
array of floating point numbers:
[[ 3.  1.]
 [-2.  4.]]


2) array can be created and gets filled with initial values (ones or zeros) using:


*   `zeros((dim1,dim2) [,type(optional)])`: fills a (dim1 x dim2) array with zeros
*   `ones((dim1,dim2) [,type(optional)])`: fills a (dim1 x dim2) array with ones



In [22]:
print('3 x 3 array with zeros:')
a = np.zeros((3,3))
print(a)
print('2 x 5 array with ones:')
b = np.ones((2,5),int)
print(b)
print('generating one-dimensional arrays')
a = np.zeros(4)
print(a)
b = np.ones(4)
print(b)


3 x 3 array with zeros:
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
2 x 5 array with ones:
[[1 1 1 1 1]
 [1 1 1 1 1]]
generating one-dimensional arrays
[0. 0. 0. 0.]
[1. 1. 1. 1.]


3) Using `arange(start, stop [,step(optional), type(optional)])` function which generate a one-dimensional array from `start` value to `stop` value (excluding) with increment `step` value. Note that the interval does not usually include `stop` value, except in some cases where step is not an integer and floating point round-off affects the length of out. `arange` works similar to `range` function but it generate an array rather than a list.

In [ ]:
a=np.arange(1,10,1)
print('a=',a)
b=np.arange(1,10,2)
print('b=',b)
b=np.arange(0,5,0.5)
print('b=',b)

a= [1 2 3 4 5 6 7 8 9]
b= [1 3 5 7 9]
b= [0.  0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5]


## Accessing and changing array element
For a rank-2 array `c`, `c[i,j]` accesses the element in row i and column j. `c[i]` refers to row i. The elements of an array can be changed by assignment.

In [ ]:
c = np.ones((3, 3)) #initial array
print(c)
print('substitute 5 for element (2,2) of the array:')
c[1,1] = 5
print(c)
print('substitute -3 for element (1,1) of the array:')
c[0,0] = -3
print(c)
print('substitute the last row with [2, 6, 9]:')
c[2] = [2, 6, 9]
print(c)
print('substitute the last 2 elements of the first row with [-5, 12]:')
c[0,1:3]=[-5,12]
print(c)
print('output the last column:')
print(c[:,2])
print('substitute the last column with [-111, 201, 305]:')
c[:,2]=[-111, 201, 305]
print(c)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
substitute 5 for element (2,2) of the array:
[[1. 1. 1.]
 [1. 5. 1.]
 [1. 1. 1.]]
substitute -3 for element (1,1) of the array:
[[-3.  1.  1.]
 [ 1.  5.  1.]
 [ 1.  1.  1.]]
substitute the last row with [2, 6, 9]:
[[-3.  1.  1.]
 [ 1.  5.  1.]
 [ 2.  6.  9.]]
substitute the last 2 elements of the first row with [-5, 12]:
[[-3. -5. 12.]
 [ 1.  5.  1.]
 [ 2.  6.  9.]]
output the last column:
[12.  1.  9.]
substitute the last column with [-111, 201, 305]:
[[  -3.   -5. -111.]
 [   1.    5.  201.]
 [   2.    6.  305.]]


### Copying arrays

If variable `a` is a mutable object, such aslists and arrays, the assignment statement `b = a` does not result in a new object `b`, but simply creates a new reference to `a` , called a *deep copy*. This means `b` is simply another name for `a` and they are essentially the same variable located in the location in the computer memory.


To make an independent copy of an array a, use the copy method in the numpy module `b=a.copy()` or by slice indexing `b[:]=a`. This is shown in the following example:


In [ ]:
a = np.array([1,2,3])
b = a  # deep copy (creates a "reference" to a only)
print('a:',a)
print('b:',b)
print('... changing a but not b')
a[:] = 5  # replace all elements in a with 5
print('a:',a)
print('b:',b)
print('Surprisingly, b also changes although we only changed a !!!')
print('This is because with b=a, a and b are the same variable and changing one results in change of the other.')

print()
print('... using copy() ...')
a = np.array([1,2,3])
b = a.copy()  #create b by copying a (creates a new variable and not a reference)
print('a:',a)
print('b:',b)
print('... changing a but not b')
a[:] = 5  # replace all elements in a with 5
print('a:',a)
print('b:',b)
print('Only a changes but b remains unchanged, since a and b are now two seperate variables')

print()
print('... using b[:]=a (slice indexing)...')
a = np.array([1,2,3])
b[:] = a # This also creates a new variable b
print('a:',a)
print('b:',b)
print('... changing a but not b')
a[:] = 5  # replace all elements in a with 5
print('a:',a)
print('b:',b)
print('Again, only a changes but b remains unchanged, because a and b are two seperate variables')

a: [1 2 3]
b: [1 2 3]
... changing a but not b
a: [5 5 5]
b: [5 5 5]
Surprisingly, b also changes although we only changed a !!!
This is because with b=a, a and b are the same variable and changing one results in change of the other.

... using copy() ...
a: [1 2 3]
b: [1 2 3]
... changing a but not b
a: [5 5 5]
b: [1 2 3]
Only a changes but b remains unchanged, since a and b are now two seperate variables

... using b[:]=a (slice indexing)...
a: [1 2 3]
b: [1 2 3]
... changing a but not b
a: [5 5 5]
b: [1 2 3]
Again, only a changes but b remains unchanged, because a and b are two seperate variables


### Obtaining the shape of an array

In [ ]:
print('Obtaining the shape of the array:')
d=np.array([[1,2,3,4],[5,6,7,8]])
print('d = \n',d)
print('shape of d: ', d.shape, ': (rows, columns) of the array)')
e=np.array([[1,2,3,4]])
print('e = \n',e)
print('shape of e: ', e.shape, ': (rows, columns) of the array)')
e=np.array([1,2,3,4]) 
print('e = \n',e)
print('shape of e: ', e.shape, ': if the array is defined as a 1D array, only the length is reported')

Obtaining the shape of the array:
d = 
 [[1 2 3 4]
 [5 6 7 8]]
shape of d:  (2, 4) : (rows, columns) of the array)
e = 
 [[1 2 3 4]]
shape of e:  (1, 4) : (rows, columns) of the array)
e = 
 [1 2 3 4]
shape of e:  (4,) : if the array is defined as a 1D array, only the length is reported


## Arithmetic operations on arrays
Arithmetic operators is applied to each element of the array.

In [ ]:
c = np.ones ((3,3)) #init the array using ones
print(c)
print('dividing all element by a number:')
c=c/4
print(c)
print('multiplying all element by a number:')
c=c*2
print(c)
print('adding/subtracting a number to/from all element:')
c=c+4
print(c)
c=c-0.5
print(c)
print('applying a numpy math function (square root):')
c=np.sqrt(c)  
print('sqrt(c)=\n',c)
print('raising the matrix to the power of 2 (element-wise, i.e., each element is raised to the power):')
c=c**2
print('c^2=\n',c)
print('square root by raising the matrix to power of 0.5 (element-wise):')
c=c**0.5 
print('c^0.5=\n',c, ' Note that it is equal to sqrt(c)')
print('multiply by 15:')
c=c*15
print('c=\n',c)
print('applying a numpy math function (sine):')
c=c*np.pi/180 # c in rad
c=np.sin(c)  
print('sin(c)=\n',c)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
dividing all element by a number:
[[0.25 0.25 0.25]
 [0.25 0.25 0.25]
 [0.25 0.25 0.25]]
multiplying all element by a number:
[[0.5 0.5 0.5]
 [0.5 0.5 0.5]
 [0.5 0.5 0.5]]
adding/subtracting a number to/from all element:
[[4.5 4.5 4.5]
 [4.5 4.5 4.5]
 [4.5 4.5 4.5]]
[[4. 4. 4.]
 [4. 4. 4.]
 [4. 4. 4.]]
applying a numpy math function (square root):
sqrt(c)=
 [[2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]]
raising the matrix to the power of 2 (element-wise, i.e., each element is raised to the power):
c^2=
 [[4. 4. 4.]
 [4. 4. 4.]
 [4. 4. 4.]]
square root by raising the matrix to power of 0.5 (element-wise):
c^0.5=
 [[2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]]  Note that it is equal to sqrt(c)
multiply by 15:
c=
 [[30. 30. 30.]
 [30. 30. 30.]
 [30. 30. 30.]]
applying a numpy math function (sine):
sin(c)=
 [[0.5 0.5 0.5]
 [0.5 0.5 0.5]
 [0.5 0.5 0.5]]


## Array functions

In [ ]:
c = np.array([[3.0, 1.0, 5],[-2.0, 4.0, 6],[8,-3, 9]])
print(c)

print('diagonal elements:')
print(np.diag(c))

print('maximum element of c:')
print(np.max(c))

print('minimum element of c:')
print(np.min(c))

print('trace of c (sum of diagonal elements):')
print(np.trace(c), ' -> = 3+4+9')

print('transpose of c (switching of elements across diagonal):')
print(c.T)




[[ 3.  1.  5.]
 [-2.  4.  6.]
 [ 8. -3.  9.]]
diagonal elements:
[3. 4. 9.]
maximum element of c:
9.0
minimum element of c:
-3.0
trace of c (sum of diagonal elements):
16.0  -> = 3+4+9
transpose of c (switching of elements across diagonal):
[[ 3. -2.  8.]
 [ 1.  4. -3.]
 [ 5.  6.  9.]]


### Matrix multiplication

Element-wise multiplication: `A*B`: multiplies the corresponsing elements of the two matrices together. `A` and `B` must have a similar shape.

In [ ]:
A = np.array([[1, 2],[0, 3]])
print('A=')
print(A)
B = np.array([[1, 3],[2, 1]])
print('B=')
print(B)

print('element-wise multiplication A*B =')
print(A*B)

A=
[[1 2]
 [0 3]]
B=
[[1 3]
 [2 1]]
element-wise multiplication A*B =
[[1 6]
 [0 3]]


Matrix product (dot product) using `dot(a,b)` function of numpy. Multiplies a (mxn) matris with a (nxp) matrix to give a (mxp) product.

In [ ]:
A = np.array([[1, 2],[0, 3]])
print('A=')
print(A)
B = np.array([[1, 3],[2, 1]])
print('B=')
print(B)
print('C= AB =')
C=np.dot(A,B)
print(C, ' note that the product is different from element-wise multiplication above')
print()

D = np.array([[2, 1],[1, 0], [3,4]])
print('D is a (3x2) matrix:\n',D)
E = np.array([[5, 2, 0, 3],[3, 4, 2, 1]])
print('E is a (2x4) matrix:\n',E)
P=np.dot(D,E)
print('P= DE =\n', P, 'P=DE is (3x2)(2x4)=(3x4) matrix')

A=
[[1 2]
 [0 3]]
B=
[[1 3]
 [2 1]]
C= AB =
[[5 5]
 [6 3]]  note that the product is different from element-wise multiplication above

D is a (3x2) matrix:
 [[2 1]
 [1 0]
 [3 4]]
E is a (2x4) matrix:
 [[5 2 0 3]
 [3 4 2 1]]
P= DE =
 [[13  8  2  7]
 [ 5  2  0  3]
 [27 22  8 13]] P=DE is (3x2)(2x4)=(3x4) matrix


Identity matrix: `identity(n)` or `eye(n)` of numpy generate a (nxn) identity matrix, which is a matrix with one on the diagonal but zero elsewhere.

In [ ]:
a=np.identity(3)
print('a=\n',a)

b=np.eye(5)
print('b=\n',b)

a=
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
b=
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


Inverse of matrix: `inv(A)` function of numpy.linalg package calculates the inverse of matrix A.

In [ ]:
A=np.array([[1,2],[5,3]])
print('A = \n',A)
C = np.linalg.inv(A)
print('C=\n',C ,': inv(A) inverse of A')
print('Check: martix product of A and inverse of should give the identity matrix (I), i.e., A(inv(A))=I ')
D=np.dot(A,C)
print('D= A inv(A) = I \n',D ,' which is (almost) equal to the identity matrix')
print('Note that the very small non-zero numbers appear due to round-off error near zero. For practical purposes they can be considered as zeros.')

A = 
 [[1 2]
 [5 3]]
C=
 [[-0.42857143  0.28571429]
 [ 0.71428571 -0.14285714]] : inv(A) inverse of A
Check: martix product of A and inverse of should give the identity matrix (I), i.e., A(inv(A))=I 
D= A inv(A) = I 
 [[ 1.00000000e+00  0.00000000e+00]
 [-3.33066907e-16  1.00000000e+00]]  which is (almost) equal to the identity matrix
Note that the very small non-zero numbers appear due to round-off error near zero. For practical purposes they can be considered as zeros.


Solving a system of equations Ax=b using `solve(a,b)` function of of numpy.linalg package to obtain x where A is a square matrix and x,b are vectors of the same size

In [ ]:
print('Solving the system of equations Ax=b to obtain x:')
A=np.array([[1,2,3],[5,3,1],[0, 2, 1]])
print('A = \n',A ,': a square (3x3) matrix')
b=np.array([2,1,4])
print('b = \n',b ,': a (3x1) vector. The number of rows must be the same as that of A')
x = np.linalg.solve(A,b) # Note that the order in which A, b is input is important
print('x = \n',x ,': gives a (3x1) matrix consistent with shape of b')
print()
print('Check: Is Ax=b satisfied??')
c=np.dot(A,x)
print('c = Ax = \n',c ,': which is equal to b. Therefore, x is the true solution to this system.')

Solving the system of equations Ax=b to obtain x:
A = 
 [[1 2 3]
 [5 3 1]
 [0 2 1]] : a square (3x3) matrix
b = 
 [2 1 4] : a (3x1) vector. The number of rows must be the same as that of A
x = 
 [-1.04761905  2.23809524 -0.47619048] : gives a (3x1) matrix consistent with shape of b

Check: Is Ax=b satisfied??
c = Ax = 
 [2. 1. 4.] : which is equal to b. Therefore, x is the true solution to this system.


Alternatively, Ax=b system cab be calulated as x=inv(A)b where inv(A) is the inverse of A

In [ ]:
Ainv = np.linalg.inv(A)
x = np.dot(Ainv,b)
print('x = \n',x ,': which is exactly similar to the x vector obtained above.')


x = 
 [-1.04761905  2.23809524 -0.47619048] : which is exactly similar to the x vector obtained above.


## Exercise
Consider the matrix $A=\begin{bmatrix}
5 & 3 & 2\\
0 & 1 & 9\\
-4 & 6 & 7\\
\end{bmatrix}$ and the vector $b=\begin{bmatrix}
11\\
3\\
2\\
\end{bmatrix}$.

1. Obtain the diagonal elements of A, along with maximum and minimum element, its trace and transpose.
2. Perform matrix multiplication $Ab$.
3. Find the inverse of $A$ (denoted as $A^{-1}$). Check to see if $AA^{-1}=I$, where $I$ is the identity matrix.
4. Calculate $(I+2A)/3$ expression.
5. Multiply $A$ by $A$: first element-wise multiplication $A*A$ and using matrix multiplication $AA$ (obviously, we don't expect the results to be the same). 
6. Calculate $A^2$ (element-wise) and then $(A^2)^{0.5}$. Is it equal to $A$?
7. Solve the system of equations $Ax=b$ to obtain vector $x$. Check to see if $Ax=b$ is satisfied with the vector $x$ you obtained.

