# Matrix inversion (using column-by-column approach)

For a square, nonsingular matrix $A$ we find the inverse matrix $A^{-1}$ such that $AA^{-1}=A^{-1}A=I$, where $I$ is the identity matrix.

We find $A^{-1}$ using the column-by-column approach which can be done efficiently via LU factorization:
* Use LU factorization to find $L$ and $U$ matrices.
* Set $b_1=[1\ 0\ 0\ \ldots]$ and solve $Ax_1=b_1$ using LU factorization to obtain $x_1$ vector. $x_1$ is the first column of $A^{-1}$.
* Repeat with $b_2=[0\ 1\ 0 \ldots]$, $b_3=[0\ 0\ 1 \ldots]$ and so on to find the subsequent columns of $A^{-1}$.



## Solution of a system using LU factorization (with partial pivoting):

Recall that to solve the system of equations $Ax=b$ using LU factorization (with partial pivoting):
* Factorize $A$ into $L$ and $U$
* Solve $Ld=Pb$ to obtain $d$ vector
* Solve $Ux=d$ to obtain $x$ vector

### Example: 

Find the inverse of the matrix $A$ given below using the column-by-column approach via LU factorization. Verify that $AA^{-1}=I$. Compare the results with python built-in `inv` function.

In [13]:
import numpy as np
from scipy.linalg import lu

A = np.array([[4., 6., 9.],[2., 1., 8.], [11., 5., 3.]])
n = A.shape[0]
Ainv = np.zeros((n,n),float)  #initiate the inverse of A as a nxn matrix with zeros

PT,L,U = lu(A)   #lu function: does LU factorization with pivoting
P = PT.T # Note that the permutation matrix if the transpose of what lu returns
         # P is the matrix keeing track of row switching not PT

print('Calc. x1:')
b1 = np.array([1., 0., 0.])
Pb = np.dot(P,b1)
d = np.linalg.solve(L,Pb)  #Ld=Pb solution
x1 = np.linalg.solve(U,d)  #Ux=d solution
Ainv[:,0] = x1  #set the first column as x1
print()
print('Calc. x2:')
b2 = np.array([0., 1., 0.])
Pb = np.dot(P,b2)
d = np.linalg.solve(L,Pb)  #Ld=Pb solution
x2 = np.linalg.solve(U,d)  #Ux=d solution
Ainv[:,1] = x2  #set the second column as x2
print()
print('Calc. x3:')
b3 = np.array([0., 0., 1.])
Pb = np.dot(P,b3)
d = np.linalg.solve(L,Pb)  #Ld=Pb solution
x3 = np.linalg.solve(U,d)  #Ux=d solution
Ainv[:,2] = x3  #set the third column as x3

print('Ainv=\n',Ainv)
print('Check: [A][Ainv]=\n', np.dot(A,Ainv) ,'=I (except for the round-off error): verified')

print()
print('Check: Ainv using python inv function:')
from scipy.linalg import inv
Ainv = inv(A)
print('Ainv=\n',Ainv)



Calc. x1:

Calc. x2:

Calc. x3:
Ainv=
 [[-0.11044776  0.08059701  0.11641791]
 [ 0.24477612 -0.25970149 -0.04179104]
 [-0.00298507  0.13731343 -0.0238806 ]]
Check: [A][Ainv]=
 [[ 1.00000000e+00 -8.32667268e-17 -3.46944695e-17]
 [-1.04083409e-17  1.00000000e+00 -2.77555756e-17]
 [-1.21864324e-16 -1.38777878e-16  1.00000000e+00]] =I (except for the round-off error): verified

Check: Ainv using python inv function:
Ainv=
 [[-0.11044776  0.08059701  0.11641791]
 [ 0.24477612 -0.25970149 -0.04179104]
 [-0.00298507  0.13731343 -0.0238806 ]]


# Exercise:

Find the inverse of the matrix $A$ given below using the column-by-column approach via LU factorization. Verify that $AA^{-1}=I$. Compare the results with python built-in `inv` function.
\begin{equation}[A]=
\begin{bmatrix}
-3 & 9 & 19 & 9\\
4 & 5 & 8 & 6\\
3 & 7 & -1 & 8 \\
1 & -6 & 12 & 3 \\
\end{bmatrix}
\end{equation}