# Numerical Partial Differentiation (incomnplete)

In numerical differentiation we find the partial derivative of function $f(x,y,...)$ numerically using the finite-difference method.

## Python function `gradient`

The function [`gradient`](https://numpy.org/doc/stable/reference/generated/numpy.gradient.html#numpy.gradient) of `numpy` library calculates the derivative using the second order accurate central differences in the interior points and either first or second order accurate one-sides (forward or backwards) differences at the boundaries. This is done using the `edge_order` which is `edge_order=1` by default.
The returned gradient hence has the same shape as the input array. `gradient` can calculate the derivative on both uniformly spaced and non-uniformly spaced independent variable array.

In [ ]:
import numpy as np
hx = 0.01 # step size in x
hy = 0.2 # step size in y
print('step size in x = ', hx)
print('step size in y = ', hy)
x = np.arange(0.,0.06,hx)   #uniformly spaced x with constant step size hx
y = np.arange(1.,2.01,hy)   #uniformly spaced x with constant step size hy
print('x = ', x) 
print('y = ', y) 
f = lambda x,y: x**2 + y**2
z = np.zeros((y.size, x.size), float)
for j in range(y.size):
  for i in range(x.size):
    z[j,i] = f(x[i],y[j])
print('z = f(x,y) = \n', z)


dzdx = np.gradient (z, hy, hx, edge_order = 2)  # partial derivative with respect to x
print('dz/dx = \n', dzdx, ' : 2nd order central finite-difference approx. of partial derivative with respect to x')
print('dz/dx = \n', dzdx[1], ' : 2nd order central finite-difference approx. of partial derivative with respect to x')
print('true value: df(x,y)/dx = ', 2 * x)
print()
# dzdx = np.gradient (z, hy, edge_order = 2)  # partial derivative with respect to x
# print('dz/dx = ', dzdx, ' : 2nd order central finite-difference approx. of partial derivative with respect to x')
# print('true value: df(x,y)/dx = ', 2 * x)

step size in x =  0.01
step size in y =  0.2
x =  [0.   0.01 0.02 0.03 0.04 0.05]
y =  [1.  1.2 1.4 1.6 1.8 2. ]
z = f(x,y) = 
 [[1.     1.0001 1.0004 1.0009 1.0016 1.0025]
 [1.44   1.4401 1.4404 1.4409 1.4416 1.4425]
 [1.96   1.9601 1.9604 1.9609 1.9616 1.9625]
 [2.56   2.5601 2.5604 2.5609 2.5616 2.5625]
 [3.24   3.2401 3.2404 3.2409 3.2416 3.2425]
 [4.     4.0001 4.0004 4.0009 4.0016 4.0025]]
dz/dx = 
 [array([[2. , 2. , 2. , 2. , 2. , 2. ],
       [2.4, 2.4, 2.4, 2.4, 2.4, 2.4],
       [2.8, 2.8, 2.8, 2.8, 2.8, 2.8],
       [3.2, 3.2, 3.2, 3.2, 3.2, 3.2],
       [3.6, 3.6, 3.6, 3.6, 3.6, 3.6],
       [4. , 4. , 4. , 4. , 4. , 4. ]]), array([[ 1.42108547e-14,  2.00000000e-02,  4.00000000e-02,
         6.00000000e-02,  8.00000000e-02,  1.00000000e-01],
       [-1.42108547e-14,  2.00000000e-02,  4.00000000e-02,
         6.00000000e-02,  8.00000000e-02,  1.00000000e-01],
       [ 0.00000000e+00,  2.00000000e-02,  4.00000000e-02,
         6.00000000e-02,  8.00000000e-02,  1.00000000e-01

# Exercise

Calculate the derivative of $f(x)=\sin(x)$ for $x=[0,2\pi]$ using the first and second order finite-difference schemes. Compare the results with the analytical solution.